---
title: "R Notebook"
output: html_notebook
---

# Setup
```{r}
# Packages
library(plyr)
library(tidyverse)
library(rJava)
library(xlsx)
library(zoo)
library(forecast)

# Working directories and file paths
#setwd("/Users/matttrombley/Desktop/Time Series II/Homework 4/")
setwd("C:\\Users\\Grant\\Downloads")
path <- "C:\\Users\\Grant\\Documents\\GitHub\\Time-Series-2-\\well.csv"

# Read in the data file
#well <- read.csv("G-1260_T.csv")
well <- read_csv(path)
```


# Converting things to 15 minute intervals
```{r}
# Create a time element that is hourly to aggregate on
well$`UTC Hour` <- as.character(well$`UTC Hour`)
well$date_hour <- paste(paste(well$`UTC Date`,substr(well$`UTC Hour`,1,nchar(well$`UTC Hour`)-3),sep=" "),":00",sep="")

# Aggregate the corrected well height data to hourly
well_agg <- aggregate(well$Corrected, list(well$date_hour), mean)
well_agg <- as.tibble(well_agg) # converting to tibble bc its a dataframe but better
well_agg <- rename(well_agg, dtime = Group.1, height = x)
well_agg$dtime <- mdy_hms(well_agg$dtime) # need lubridate library to make this work
class(well_agg$dtime) # looks like POSIX!
well_agg$dtime <- format(round(well_agg$dtime, units="hours"), format="%m/%d/%y %H")
well_agg$dtime <- as.character(well_agg$dtime)
well_agg <- well_agg %>% # aggregating on hour and averaging things
  group_by(dtime) %>% 
  summarise(avg_height = mean(height)) 
well_agg$dtime <- mdy_h(well_agg$dtime) # looks good! 
```




